name: WASM CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v6
      with:
        version: 1.39.16
    - name: make wasm
      run: |
        cd src
        make ARCH=wasm build
